[package]
name = "rust-cli-chat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "server/mod.rs"

[[bin]]
name = "client"
path = "client/mod.rs"

[dependencies]
tokio = { version = "1.29.0", features = ["net", "rt", "macros", "rt-multi-thread", "io-util", "sync", "io-std"] }
